version: '3.8'
services:
  article-bdd:
    build:
      context: "./articles-db"
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - articlebdd:/var/lib/mysql
volumes:
  articlebdd: